require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HoundsController do

  def mock_hound(stubs={})
    @mock_hound ||= mock_model(Hound, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all hounds as @hounds" do
      Hound.stub(:all) { [mock_hound] }
      get :index
      assigns(:hounds).should eq([mock_hound])
    end
  end

  describe "GET show" do
    it "assigns the requested hound as @hound" do
      Hound.stub(:find).with("37") { mock_hound }
      get :show, :id => "37"
      assigns(:hound).should be(mock_hound)
    end
  end

  describe "GET new" do
    it "assigns a new hound as @hound" do
      Hound.stub(:new) { mock_hound }
      get :new
      assigns(:hound).should be(mock_hound)
    end
  end

  describe "GET edit" do
    it "assigns the requested hound as @hound" do
      Hound.stub(:find).with("37") { mock_hound }
      get :edit, :id => "37"
      assigns(:hound).should be(mock_hound)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created hound as @hound" do
        Hound.stub(:new).with({'these' => 'params'}) { mock_hound(:save => true) }
        post :create, :hound => {'these' => 'params'}
        assigns(:hound).should be(mock_hound)
      end

      it "redirects to the created hound" do
        Hound.stub(:new) { mock_hound(:save => true) }
        post :create, :hound => {}
        response.should redirect_to(hound_url(mock_hound))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hound as @hound" do
        Hound.stub(:new).with({'these' => 'params'}) { mock_hound(:save => false) }
        post :create, :hound => {'these' => 'params'}
        assigns(:hound).should be(mock_hound)
      end

      it "re-renders the 'new' template" do
        Hound.stub(:new) { mock_hound(:save => false) }
        post :create, :hound => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hound" do
        Hound.stub(:find).with("37") { mock_hound }
        mock_hound.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :hound => {'these' => 'params'}
      end

      it "assigns the requested hound as @hound" do
        Hound.stub(:find) { mock_hound(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:hound).should be(mock_hound)
      end

      it "redirects to the hound" do
        Hound.stub(:find) { mock_hound(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(hound_url(mock_hound))
      end
    end

    describe "with invalid params" do
      it "assigns the hound as @hound" do
        Hound.stub(:find) { mock_hound(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:hound).should be(mock_hound)
      end

      it "re-renders the 'edit' template" do
        Hound.stub(:find) { mock_hound(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hound" do
      Hound.stub(:find).with("37") { mock_hound }
      mock_hound.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the hounds list" do
      Hound.stub(:find) { mock_hound }
      delete :destroy, :id => "1"
      response.should redirect_to(hounds_url)
    end
  end

end
